### ISSUE TITLE
cron-connector container stops working after removing a function (faasd)

### ISSUE THREAD

**Issue by DriesCruyskens** [zeerorg/cron-connector#25]
I am successfully running cron-connector in conjunction with Faasd using the attached docker-compose.yml file (see below, copied from official Serverless for Everyone Else book).

Deploying functions with cron annotations works great:

```yaml
annotations:
      topic: cron-function
      schedule: "*/1 * * * *"
```

As we can see in the cron-connector's logs:

````bash
$ sudo journalctl -f -u containerd | grep cron-connector
Jun 02 19:45:23 faasd openfaas:cron-connector[12716]: 2022/06/02 17:45:23 Gateway URL: http://gateway:8080
Jun 02 19:45:23 faasd openfaas:cron-connector[12716]: 2022/06/02 17:45:23 Async Invocation: false
Jun 02 19:45:33 faasd openfaas:cron-connector[12716]: 2022/06/02 17:45:33 Registered: golang.openfaas-fn [*/1 * * * *]
Jun 02 19:46:00 faasd openfaas:cron-connector[12716]: 2022/06/02 17:46:00 Executing function: golang.openfaas-fn
Jun 02 19:46:00 faasd openfaas:cron-connector[12716]: 2022/06/02 17:46:00 Response: golang [200]
````

However, as soon as I remove a function, there is an error:

```shell
...
Jun 02 20:36:00 faasd openfaas:cron-connector[15848]: 2022/06/02 18:36:00 Executing function: golang.openfaas-fn
Jun 02 20:36:00 faasd openfaas:cron-connector[15848]: 2022/06/02 18:36:00 Response: golang [200]
<other session: $ faas-cli remove golang>
Jun 02 20:36:14 faasd openfaas:cron-connector[15848]: Error: can't list functions: server returned unexpected status code: 500 - Metrics hander: unexpected status code retrieving functions from backend
Jun 02 20:36:14 faasd openfaas:cron-connector[15848]: 
```

Once this happens, no functions is ever triggered by cron-connector anymore until executing: `systemctl restart faasd`

- The same happens when removing the function using the gateway UI instead of the CLI. 
- Setting a `restart: always` policy on the `cron-connector` docker-compose service does not help either. 
- It doesn't matter if there are functions left to run or not, deleting 1 function triggers the error.
- I am not able to track this error message to a particular line in the cron-connector's source code..

<details>
  <summary>stack.yml</summary>
  
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.64.15:8080
functions:
  golang:
    lang: go
    handler: ./golang
    image: driescruyskens/golang:latest
    annotations:
      topic: cron-function
      schedule: "*/1 * * * *"
```
</details>

<details>
  <summary>docker-compose file</summary>
  
```yaml
version: "3.7"
services:
  cron-connector:
    image: "ghcr.io/openfaas/cron-connector:latest"
    environment:
      - gateway_url=http://gateway:8080
      - basic_auth=true
      - secret_mount_path=/run/secrets
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - gateway
      
  basic-auth-plugin:
    image: ghcr.io/openfaas/basic-auth:0.21.4
    environment:
      - port=8080
      - secret_mount_path=/run/secrets
      - user_filename=basic-auth-user
      - pass_filename=basic-auth-password
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW

  nats:
    image: docker.io/library/nats-streaming:0.22.0
# nobody
    user: "65534"
    command:
      - "/nats-streaming-server"
      - "-m"
      - "8222"
      - "--store=file"
      - "--dir=/nats"
      - "--cluster_id=faas-cluster"
    volumes:
# Data directory
      - type: bind
        source: ./nats
        target: /nats
    # ports:
    #    - "127.0.0.1:8222:8222"

  prometheus:
    image: docker.io/prom/prometheus:v2.14.0
# nobody
    user: "65534"
    volumes:
# Config directory
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
# Data directory
      - type: bind
        source: ./prometheus
        target: /prometheus
    cap_add:
      - CAP_NET_RAW
    ports:
       - "127.0.0.1:9090:9090"

  gateway:
    image: ghcr.io/openfaas/gateway:0.21.4
    environment:
      - basic_auth=true
      - functions_provider_url=http://faasd-provider:8081/
      - direct_functions=false
      - read_timeout=60s
      - write_timeout=60s
      - upstream_timeout=65s
      - faas_nats_address=nats
      - faas_nats_port=4222
      - auth_proxy_url=http://basic-auth-plugin:8080/validate
      - auth_proxy_pass_body=false
      - secret_mount_path=/run/secrets
      - scale_from_zero=true
      - function_namespace=openfaas-fn
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - basic-auth-plugin
      - nats
      - prometheus
    ports:
       - "8080:8080"

  queue-worker:
    image: ghcr.io/openfaas/queue-worker:0.12.2
    environment:
      - faas_nats_address=nats
      - faas_nats_port=4222
      - gateway_invoke=true
      - faas_gateway_address=gateway
      - ack_wait=5m5s
      - max_inflight=1
      - write_debug=false
      - basic_auth=true
      - secret_mount_path=/run/secrets
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - nats
```
</details>
